openapi: 3.0.0
info:
  title: 'API tutoriel'
  version: 1.0.0
servers:
  -
    url: 'http://api.tuoriel.fr/v1'
    description: 'Mon api'
paths:
  /posts:
    get:
      operationId: dca0ee1ff314f3065b781be0a527a9d9
      responses:
        '200':
          description: 'Nos articles'
          content:
            application/json:
              schema:
                description: 'Titre du premier article'
                type: string
